name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Specify your default branch
  pull_request:
    branches:
      - main  # Specify your default branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # Your Docker Hub username
          password: ${{ secrets.DOCKER_PASSWORD }}  # Your Docker Hub password

      - name: Build Docker image
        run: |
          docker build -t yourusername/your-django-app:latest .  # Replace with your Docker Hub image name

      - name: Push Docker image
        run: |
          docker push yourusername/your-django-app:latest  # Replace with your Docker Hub image name